spring:
  application:
    name: ct-demo

logging:
  level:
    org.springdoc: DEBUG

commercetools:
  project-key: test-project
  client-id: dummy
  client-secret: dummy
  auth-url: http://localhost:8989/oauth/token
  api-url: http://localhost:8989


