spring:
  application:
    name: dt-demo
  context:
    initializers:
      - at.ct.mock.demo.server.CommercetoolsMockServerRuntimeInitializer

server:
  port: 8080

springdoc:
  swagger-ui:
    url: customer-api.yaml

logging:
  level:
    org.springdoc: DEBUG

commercetools:
  project-key: test-project
  client-id: dummy
  client-secret: dummy
  auth-url: http://commercetools:1234/oauth/token
  api-url: http://commercetools:1234

customer-service:
  api-url: http://localhost:8080/api
  user: dummy
  password: dummy

