openapi: 3.1.0
info:
  title: Customer API
  version: 1.0.0
  description: API to manage and update customer information

servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /customers/{key}:
    get:
      summary: Get a customer by key
      description: Retrieve customer information by unique key
      operationId: getCustomer
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Unique key of the customer
      responses:
        '200':
          description: Customer retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Customer not found
        '500':
          description: Server error

    put:
      summary: Update a single customer
      description: Update customer information by key
      operationId: updateCustomer
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Unique key of the customer
      requestBody:
        description: Customer update object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdate'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: Invalid request
        '404':
          description: Customer not found
        '500':
          description: Server error

components:
  schemas:
    CustomerUpdate:
      type: object
      required:
        - key
      properties:
        key:
          type: string
          description: Unique key of the customer
          example: customer-1
        firstName:
          type: string
          description: Customer first name
          example: John
        lastName:
          type: string
          description: Customer last name
          example: Doe

    CustomerResponse:
      type: object
      properties:
        key:
          type: string
          description: Unique key of the customer
          example: customer-1
        firstName:
          type: string
          description: Customer first name
          example: John
        lastName:
          type: string
          description: Customer last name
          example: Doe
        updatedAt:
          type: string
          format: date-time
          description: Timestamp of the last update
          example: 2025-09-17T15:34:00Z
